/**
 * Saltwater Fish Pro | Publication information pages
 * Clear standards and disclosures make the editorial model legible before any commercial recommendation.
 */

import { Mail, ShieldCheck } from "lucide-react";
import { Link, useLocation } from "wouter";
import { SiteHeader } from "@/components/SiteHeader";
import { SiteFooter } from "@/components/SiteFooter";
import { StabilityThreadNav } from "@/components/StabilityThreadNav";
import { useSeo } from "@/lib/useSeo";

const info = {
  "/about": { eyebrow: "About Saltwater Fish Pro", title: "A field guide for healthier mixed saltwater systems.", description: "Saltwater Fish Pro is an editorial publication for people building, caring for, and improving mixed saltwater aquariums.", sections: [["Purpose", "We publish stability-first guidance that connects planning, water, equipment, livestock, and care. The goal is not to make every system look the same. It is to make the next decision clearer, calmer, and more defensible."], ["Editorial approach", "The publication favors context over universal product lists. Articles explain the assumed system, trade-offs, practical limits, and what should be observed next. We do not present generic internet summaries as hands-on testing."], ["Important scope", "Content is educational and general in nature. It is not a diagnosis or a substitute for qualified aquatic-veterinary advice, species-specific research, or local safety guidance."]]},
  "/editorial-standards": { eyebrow: "Editorial standards", title: "Trust is part of a healthy system.", description: "How Saltwater Fish Pro researches, reviews, updates, and discloses editorial guidance.", sections: [["How we publish", "Each guide is assigned a specific reader decision, reviewed for clear assumptions and practical limits, and dated when first published. Articles are updated when materially revised—not merely to make them appear new."], ["Evidence and sources", "When a claim depends on external expertise or guidance, we link readers to the source. When an article includes first-hand observation, it should state what was observed, under what system conditions, and what remains uncertain."], ["Products and partnerships", "Commercial relationships never determine an editorial conclusion. A paid placement, gifted item, affiliate link, or other material connection must be disclosed clearly where a reader sees the recommendation. We do not publish fabricated ratings, testimonials, or test results."], ["Corrections", "If a published guide contains a material factual error, contact the editorial desk. Corrections and substantive updates will be made transparently when verified."]]},
  "/disclosure": { eyebrow: "Affiliate disclosure", title: "Recommendations should be useful before they are commercial.", description: "How Saltwater Fish Pro handles affiliate links, sponsored work, and editorial independence.", sections: [["Current status", "Saltwater Fish Pro is preparing for future affiliate and partner relationships. Until a specific commercial relationship is active, a page should not imply a commission, sponsorship, or product test that does not exist."], ["When affiliate links are active", "A clear disclosure will appear with the recommendation itself. Where Amazon links are used, the site will state: “As an Amazon Associate I earn from qualifying purchases.” Affiliate compensation does not change the editorial standard: recommendations must explain context, trade-offs, and alternatives."], ["Sponsored work and supplied products", "Sponsored content, gifted products, paid placements, and other material connections will be identified clearly and conspicuously. Editorial opinions must remain accurate, and paid relationships will not be presented as independent testing."]]},
  "/privacy": { eyebrow: "Privacy", title: "A straightforward approach to reader data.", description: "How Saltwater Fish Pro currently handles site analytics, email collection, and reader contact.", sections: [["Analytics", "The site uses privacy-conscious analytics to understand aggregate activity such as page views and guide navigation. The purpose is to improve the publication, not to sell individual reader profiles."], ["Email", "Email collection will be activated through HubSpot only after the newsletter form is configured. At that point, the form will state what readers are signing up for and provide the applicable unsubscribe and privacy information."], ["Contact", "If you contact Saltwater Fish Pro by email, use the address listed on the contact page. Do not send sensitive personal, account, or payment information through an ordinary contact email."]]},
  "/contact": { eyebrow: "Contact the publication", title: "A thoughtful question can improve the next guide.", description: "Contact Saltwater Fish Pro with corrections, editorial questions, and responsible partnership inquiries.", sections: [["Editorial and corrections", "For a factual correction, include the page URL, the statement in question, and any source that helps verify the issue. Clear documentation helps us review requests efficiently."], ["Partnership inquiries", "Partnerships must preserve editorial independence and be disclosed clearly. Do not request undisclosed endorsements, invented reviews, or claims that cannot be substantiated."], ["Production contact", "A public editorial contact address will be added before the production launch. Until it is configured, Saltwater Fish Pro does not publish a public email endpoint. Please do not send sensitive personal, payment, or medical information through an ordinary contact channel."]]},
} as const;

export default function PublicationInfo() {
  const [location] = useLocation();
  const page = info[location as keyof typeof info] ?? info["/about"];
  useSeo({ title: `${page.eyebrow} | Saltwater Fish Pro`, description: page.description, path: location, schema: { "@context": "https://schema.org", "@type": "WebPage", name: page.eyebrow, description: page.description, url: `https://saltwaterfishpro.com${location}` } });

  return <div className="site-shell publication-info"><SiteHeader /><main><StabilityThreadNav /><section className="info-hero"><div><nav className="breadcrumbs" aria-label="Breadcrumb"><Link href="/">Field guide</Link><span>/</span><span>{page.eyebrow}</span></nav><span className="eyebrow eyebrow--teal">{page.eyebrow}</span><h1>{page.title}</h1><p>{page.description}</p></div><ShieldCheck aria-hidden="true" size={64} strokeWidth={1.1} /></section><section className="info-content">{page.sections.map(([heading, copy]) => <article key={heading}><span className="eyebrow eyebrow--teal">Saltwater Fish Pro</span><h2>{heading}</h2><p>{copy}</p></article>)}<div className="info-next"><Mail size={20} /><p>Want a more useful field guide? See the <Link href="/guides">published guides</Link> or contact the editorial desk with a correction.</p></div></section></main><SiteFooter /></div>;
}
